---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  ATTENDEE_SERVICE_URL:

inputs:
- name: pcf-springboot-demo-source

run:
  path: pcf-springboot-demo-source/ci/tasks/smoke-test.sh