---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: "latest"

params:
  URL:

inputs:
- name: pcf-springboot-demo-source

run:
  path: pcf-springboot-demo-source/ci/tasks/web-test-connected.sh