---
resources:
- name: pcf-springboot-demo-source
  type: git
  source:
    uri: https://github.com/auramirea/pcf-springboot-demo
    branch: master

- name: push-to-pcf
  type: cf
  source:
    api: {{cf-endpoint}}
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}

- name: timer
  type: time
  source: {interval: 24h}

jobs:
- name: unit-test
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
  - get: timer
    trigger: true
  - task: test
    file: pcf-springboot-demo-source/ci/tasks/unit-test.yml

- name: push-connected
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
    passed: [unit-test]
  - get: timer
    trigger: true
    passed: [unit-test]
  - task: package
    file: pcf-springboot-demo-source/ci/tasks/package.yml
  - put: push-to-pcf
    params:
      manifest: pcf-springboot-demo-source/manifest-connected.yml
      path: package-output/pcf-springboot-demo.jar

- name: push-disconnected
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
    passed: [unit-test]
  - get: timer
    trigger: true
    passed: [unit-test]
  - task: package
    file: pcf-springboot-demo-source/ci/tasks/package.yml
  - put: push-to-pcf
    params:
      manifest: pcf-springboot-demo-source/manifest-disconnected.yml
      path: package-output/pcf-springboot-demo.jar

- name: test-connected
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
    passed: [push-connected]
  - get: timer
    trigger: true
    passed: [push-connected]
  - task: test-disconnected
    file: pcf-springboot-demo-source/ci/tasks/web-test-connected.yml
    params:
      URL: http://pcf-springboot-demo.cfapps.io

- name: test-disconnected
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
    passed: [push-disconnected]
  - get: timer
    trigger: true
    passed: [push-disconnected]
  - task: test-disconnected
    file: pcf-springboot-demo-source/ci/tasks/web-test-disconnected.yml
    params:
      URL: http://pcf-springboot-demo-disconnected.cfapps.io
  