---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: pcf-springboot-demo-source
  type: git
  source:
    uri: https://github.com/benwilcock/pcf-springboot-demo
    branch: master

- name: push
  type: cf
  source:
    api: {{cf-endpoint}}
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}

- name: timer
  type: time
  source: {interval: 24h}

- name: slack-alert
  type: slack-notification
  source:
    url: {{webhook}}
    insecure: true

jobs:
- name: test
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
  - get: timer
    trigger: true
  - task: test
    file: pcf-springboot-demo-source/ci/tasks/test.yml

- name: package-connected
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
    passed: [test]
  - get: timer
    trigger: true
    passed: [test]
  - task: package
    file: pcf-springboot-demo-source/ci/tasks/package.yml
  - put: push
    params:
      manifest: pcf-springboot-demo-source/manifest.yml
      path: package-output/pcf-springboot-demo.jar
  - put: slack-alert
    params:
      text: |
        The $BUILD_PIPELINE_NAME.$BUILD_JOB_NAME was pushed.

- name: package-disconnected
  public: true
  plan:
  - get: pcf-springboot-demo-source
    trigger: true
    passed: [test]
  - get: timer
    trigger: true
    passed: [test]
  - task: package
    file: pcf-springboot-demo-source/ci/tasks/package.yml
  - put: push
    params:
      manifest: pcf-springboot-demo-source/manifest-disconnected.yml
      path: package-output/pcf-springboot-demo.jar
  - put: slack-alert
    params:
      text: |
        The $BUILD_PIPELINE_NAME.$BUILD_JOB_NAME was pushed.

#  SHPEC is proving to be a bit of a dissapointment.
#  It's executing all shpec based tests in all folders, so the test stage always fails.
#  Probably need to switch to something else for testing that's a bit more production ready.


#- name: connected_test
#  public: true
#  plan:
#  - get: pcf-springboot-demo-source
#    trigger: true
#    passed: [package-connected]
#  - get: timer
#    trigger: true
#    passed: [package-connected]
#  - task: smoke_test
#    file: pcf-springboot-demo-source/ci/tasks/smoke-test.yml
#    params:
#      URL: {{smoke-test-url}}
#  - put: slack-alert
#    params:
#      text: |
#        The smoke test for $BUILD_PIPELINE_NAME (connected) has passed.
#
#- name: smoke_test_disconnected
#  public: true
#  plan:
#  - get: pcf-springboot-demo-source
#    trigger: true
#    passed: [deploy]
#  - get: 24h
#    trigger: true
#    passed: [deploy]
#  - task: smoke_test_disconnected
#    file: pcf-springboot-demo-source/ci/tasks/smoke-test-disconnected.yml
#    params:
#      URL: {{smoke-test-disconnected-url}}
#  - put: slack-alert
#    params:
#      text: |
#        The smoke test for $BUILD_PIPELINE_NAME (disconnected) has passed.